#!/bin/bash



# start carbon data collection daemon - default port: 2003 --------------------
mkdir -p /var/log/carbon
/opt/graphite/bin/carbon-cache.py start --logdir=/var/log/carbon




# start graphite web app cgi server -------------------------------------------
python /opt/graphite/webapp/graphite/manage.py runfcgi host=127.0.0.1 port=8080




service nginx start


read
